import type { Metadata } from "next";
import { Work_Sans, Space_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/widgets/Footer";
import Header from "@/widgets/header/Header";

const workSans = Work_Sans({
  weight: ['400', '600', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.className} antialiased bg-bg`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
